name: Test on Native
on:
  push:
    branches: [master]

permissions: write-all

jobs:
  test-compiler-majours:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]            

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'file'
        fetch-depth: '0'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Pybind11 install
      run: > 
        git clone https://github.com/pybind/pybind11 submod

    - name: pip
      run: pip install pybind11
        
    - name: Configure CMake
      run: >
        cmake -B build -S . -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
    - name: Build
      run: |
        cmake --build ./build

    - name: Test
      run: |
        python ./Test.py

    - name: Configure Git
      run: |
        git config user.name "BOT"
        git config user.email "a@a.com"

    - name: Git Add Build Output
      run: |
        git add .

    - name: Git Commit Build
      run: |
        git commit -m "[CI/CD] Generated plugin build automation"

    - name: Push Changes
      run: |
        git fetch
        git pull
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kenter7317/CoMusic file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
