name: Test on Native
on:
  push:
    branches: [file]
    
jobs:
  test-compiler-majours:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'file'
        fetch-depth: '0'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Pybind11 install
      run: > 
        brew install pybind11
        
    - name: Configure CMake
      run: >
        cmake -B build -S .

    - name: Build
      run: |
        cmake --build ./build --config ${{ matrix.build_type }}

    - name: Test
      run: |
        ctest --test-dir build -C ${{ matrix.build_type }}
