name: Test on Native
on:
  push:
    branches: [separation]

permissions: write-all

jobs:
  test-compiler-majours:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'master'
        fetch-depth: '0'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name: Pybind11 install
      run: > 
        git clone https://github.com/ae3f-devel/VidList ./VideoList/VidList
        
    - name: Configure CMake
      run: >
        cmake 
        -B build 
        -S./VideoList/VidList 
        -GNinja -DCMAKE_C_COMPILER=clang 
        -DCMAKE_CXX_COMPILER=clang++ 
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=../VideoList/lib
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=../VideoList/lib

    - name: Build
      run: |
        cmake --build ./build
    - name: Test
      run: |
        python ./Test.py
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./VideoList/lib

