name: build_dependency
on:
  push:
    branches: ${{ github.ref }}

permissions: write-all

jobs:
  test-compiler-majours:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: '1'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name: Pybind11 install
      run: > 
        git clone https://github.com/ae3f-devel/VidList ./VideoList/VidList
        
    - name: Setup Python
      uses: actions/setup-python@v5.6.0
      with:
        python-version: 3.13
        
    - name: Configure CMake
      run: cmake -B build -S./VideoList/VidList -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DOUTDIR=../lib

    - name: Build
      run: |
        cmake --build ./build
    - name: Test
      run: |
        python ./Test.py
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ matrix.os }}
        path: ./VideoList/lib/*



